boards/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path('admin/', admin.site.urls),
]

core/urls.py
from django.urls import path
from users import views as uesr_view

app_name = "core"

urlpatterns = [
    path("", uesr_view.HomeView.as_view(), name="home"),
]

users/urls.py
from django.urls import path
from . import views
app_name = "users"

urlpatterns = [

    path("signup", views.SignUpView.as_view(), name="signup"),
    path("login", views.LogInView.as_view(), name="login"),
]

boards/models.py
from django.db import models

# Create your models here.

class Board(models.Model):
    board_id = models.CharField(max_length=50, unique=True, null=True)
    content = models.CharField(max_length=200)
    create_time = models.DateTimeField(auto_now_add=True) 
    update_time = models.DateTimeField(auto_now=True)

comments/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models


class TimeStampModel(models.Model):

    """ Time Stamped Model """

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

follows/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class User(AbstractUser):
    """ User Model """
    GENDER_CHOICES = (
        ('m', "Male"),
        ('F', "Female"),
        ('C', "Custom"),
    )

    name = models.CharField(max_length=50)
    username = models.CharField(max_length=100, unique=True)
    photo = models.ImageField(blank=True)
    website = models.URLField(blank=True)
    bio = models.TextField(blank=True)
    email = models.CharField(blank=True, max_length=255)
    phone = models.CharField(blank=True, max_length=255)
    gender = models.CharField(
        blank=True, choices=GENDER_CHOICES, max_length=255)
    followers = models.ManyToManyField("self")
    following = models.ManyToManyField("self")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("model_detail", kwargs={"pk": self.pk})

users/forms.py
import phonenumbers
from django import forms
from . import models


class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error(
                    "password", forms.ValidationError("PASSWORD IS WRONG"))
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError("USER DOESNT EXIST"))


class SignUpForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ('email', 'name', 'username', 'password')

        widgets = {
            'password': forms.PasswordInput()
        }

    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        username = self.cleaned_data.get("username")
        email = self.cleaned_data.get("email")
        name = self.cleaned_data.get("name")
        password = self.cleaned_data.get("password")
        user.set_password(password)
        user.save()

boards/views.py
from django.shortcuts import render

# Create your views here.

comments/views.py
from django.shortcuts import render

# Create your views here.

core/views.py
from django.shortcuts import render

# Create your views here.

follows/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.views import View
from django.views.generic import FormView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from . import forms


class HomeView(View):
    def get(self, request):
        return render(request, "base.html")


class SignUpView(FormView):

    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, email=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)


class LogInView(FormView):
    template_name = "users/login.html"
    form_class = forms.LoginForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        email = form.cleaned_data.get("email", None)
        password = form.cleaned_data.get("password", None)
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)


def log_out(request):
    logout(request)
    return redirect(reverse("core:home"))

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block page_title %}{% endblock page_title %} | Instagram</title>
  </head>
  <body>
    success
    {% block content %} {% endblock %} {% include "partials/footer.html" %}
  </body>
</html>

templates/partials/footer.html
<footer>&copy; imstagram</footer>

templates/partials/nav.html
<a href="{% url "core:home"%}">Airbnb</a>
  <ul>
    
    {% if user.is_authenticated %}
    <li>
      <a href="{% url "users:logout" %}">Logout</a></li>
    {% else %}
    <li>
      <a href="{% url "users:login" %}">Login</a></li>
      <a href="{% url "users:signup" %}">Sign up</a></li>

    {% endif %}
  </ul>


templates/users/login.html
{% extends "base.html" %} {% block page_title %} Log In {%endblock page_title%}
{% block search-bar %} {% endblock search-bar %} {% block content %} 
Hello!
<form method="POST" action"{% url "users:login" %}">
    {% csrf_token %}
    {{form.as_p}}
    <button>login</button>
</form>




{% endblock content%}

templates/users/signup.html
{% extends "base.html" %} {% block page_title %} Sing up {%endblock page_title%}
{% block search-bar %} {% endblock search-bar %} {% block content %} 
Hello!
<form method="POST" action"{% url "users:signup" %}">
    {% csrf_token %}
    {{form.as_p}}
    <button>Sign up</button>
</form>




{% endblock content%}